
package com.topografix.gpx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GpxInterface", targetNamespace = "http://www.topografix.com/gpx")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GpxInterface {


    /**
     * 
     * @param request
     * @return
     *     returns com.topografix.gpx.CommandResponseData
     * @throws GpxException
     */
    @WebMethod(operationName = "ExecuteCommand")
    @WebResult(name = "CommandResponseData", targetNamespace = "http://www.topografix.com/gpx", partName = "response")
    public CommandResponseData executeCommand(
        @WebParam(name = "CommandRequestData", targetNamespace = "http://www.topografix.com/gpx", partName = "request")
        CommandRequestData request)
        throws GpxException
    ;

}
