
package com.topografix.gpx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * The location defined in soap:address is never used and has no relevance. It serves as a pattern for the SOAP request to see how it could look like, with the web service 'GpxService'
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GpxService", targetNamespace = "http://www.topografix.com/gpx", wsdlLocation = "file:/D:/Tests/Simulation/ant/ws_generation_tool/wsdl_modified/gpx.wsdl")
public class GpxService
    extends Service
{

    private final static URL GPXSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Tests/Simulation/ant/ws_generation_tool/wsdl_modified/gpx.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GPXSERVICE_WSDL_LOCATION = url;
    }

    public GpxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GpxService() {
        super(GPXSERVICE_WSDL_LOCATION, new QName("http://www.topografix.com/gpx", "GpxService"));
    }

    /**
     * 
     * @return
     *     returns GpxInterface
     */
    @WebEndpoint(name = "GpxSoapPort")
    public GpxInterface getGpxSoapPort() {
        return (GpxInterface)super.getPort(new QName("http://www.topografix.com/gpx", "GpxSoapPort"), GpxInterface.class);
    }

}
